/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Report server version, resolved model/settings state, and whether
         *     a compile is currently expected to succeed.
         *
         *     ``compile_ready`` is ``False`` -- with a human-readable string
         *     appended to ``blockers`` for each contributing reason -- whenever
         *     any of: no model has been configured *and* dry run is off; ``uv`` is
         *     not on ``PATH``; the resolved workspace directory is not writable;
         *     this application's own settings file exists but could not be read;
         *     or an inherited settings file exists but could not be parsed.
         *     Otherwise ``compile_ready`` is ``True`` and ``blockers`` is empty.
         *
         *     Every message here is written for someone who has only ever seen this
         *     application: they name this application's own controls ("Model settings",
         *     "Dry run mode") rather than a file or variable belonging to something
         *     else. The inherited configuration is still read -- a user who has one
         *     keeps working exactly as before -- but it is never presented as a
         *     requirement.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Graphs Route
         * @description List every saved graph as a summary, plus one entry per file that
         *     failed to parse/validate -- a single bad file never 500s the whole
         *     listing (``store.graphs.list_graphs``'s own contract).
         */
        get: operations["list_graphs_route_api_graphs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/{graph_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph Route
         * @description Return the full graph document.
         *
         *     404 (naming the resolved path that was checked) when no such graph
         *     exists; 422 for a malformed/path-unsafe id, or for a graph file that
         *     is not valid JSON or fails :class:`SwarmGraph` validation (a client's
         *     own bad write, or a file corrupted by an interrupted process -- never
         *     an uncaught exception reaching the ASGI stack); 500 for any other
         *     filesystem failure while reading.
         */
        get: operations["get_graph_route_api_graphs__graph_id__get"];
        /**
         * Put Graph Route
         * @description Validate + atomically write a graph document.
         *
         *     The path id is authoritative: a body ``id`` that disagrees with the
         *     path parameter is rejected with 422 naming both, rather than
         *     silently overwritten or silently accepted. ``updated_at`` is always
         *     server-stamped to ``datetime.now(UTC)`` on every successful write,
         *     overwriting whatever placeholder the client sent -- the response
         *     body reflects the stamp that was actually persisted.
         *
         *     Body validation against :class:`SwarmGraph` (including its
         *     ``_check_structural_integrity`` model validator) happens
         *     automatically via the ``graph: SwarmGraph`` parameter annotation
         *     before this function body even runs; a validation failure surfaces
         *     as FastAPI's normal 422 with no extra handling needed here.
         */
        put: operations["put_graph_route_api_graphs__graph_id__put"];
        post?: never;
        /**
         * Delete Graph Route
         * @description Remove the graph document; also remove its generated project
         *     directory when ``?project=true`` is given (idempotent -- a project
         *     that was never compiled is not an error).
         *
         *     404 when the graph itself does not exist (the ``?project`` flag
         *     never changes that: a missing graph is always a 404 regardless of
         *     whether a project directory happens to exist for that id).
         */
        delete: operations["delete_graph_route_api_graphs__graph_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/{graph_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Graph Route
         * @description Run the Phase-1 static review over a saved graph.
         *
         *     This is the "initial review" a user triggers before compiling: cycles,
         *     unreachable nodes, state ownership, port-type mismatches, branch
         *     consistency, and the rest of the structural rules.
         *
         *     **Lazy import, deliberately -- this is a degradation seam.** The whole
         *     ``swarm_builder.compile`` subsystem exists only to serve the compile
         *     and review endpoints, and it is much heavier than the rest of the
         *     server (it pulls in the codegen, agent and pipeline modules). Importing
         *     it at module level would make a broken compile subsystem take the
         *     entire server down at startup; importing it here means that subsystem
         *     fails *this endpoint* alone, with a clear 503, while graph CRUD,
         *     templates, models and health keep working.
         */
        post: operations["review_graph_route_api_graphs__graph_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description Return the template catalog's five picker-facing fields.
         *
         *     Raises:
         *         fastapi.HTTPException: 503 if the template registry cannot be
         *             imported, so one broken subsystem fails this route rather
         *             than server startup.
         */
        get: operations["list_templates_api_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/database-starters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Database Starters
         * @description Return one starter entry per database kind, in catalog order.
         *
         *     Raises:
         *         fastapi.HTTPException: 503 if the database starter catalog cannot be
         *             read, so one broken subsystem fails this route rather than server
         *             startup.
         */
        get: operations["list_database_starters_api_database_starters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models
         * @description List every configured harness route plus the resolved default,
         *     for a model picker UI.
         *
         *     A route is only ever read from a :class:`Settings` whose ``error``
         *     is ``None`` (a settings file that failed to parse contributes zero
         *     routes, matching :func:`resolve_effective_model`'s own fallthrough
         *     behavior) -- but ``settings_error`` itself is still reported
         *     verbatim so the picker can explain why the route list is empty.
         */
        get: operations["get_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Everything the model-settings screen renders.
         *
         *     Reads the file fresh: a user can edit ``workspace/settings.json`` (or flip
         *     the dry-run switch from another tab) between two requests.
         */
        get: operations["get_settings_api_settings_get"];
        /**
         * Put Settings
         * @description Save the in-app model configuration and/or the dry-run switch.
         *
         *     Validation happens before anything is written, so a rejected submission
         *     leaves the previous configuration exactly as it was. On success the
         *     credential is published into this server's environment immediately (see
         *     :func:`swarm_builder.runtime.publish_secrets`), which is what makes the
         *     change take effect for the next generate/compile/run without a restart.
         *
         *     Raises:
         *         HTTPException: 422 with every problem found, or 500 when the settings
         *             file cannot be written (an unwritable workspace).
         */
        put: operations["put_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description Make one minimal model call and report whether it worked.
         *
         *     A brand-new user's first question is "did I paste the key correctly?", and
         *     the honest answer requires a real call -- the keyless validation gate a
         *     compile runs cannot answer it, because it injects a test model on purpose.
         *
         *     Every provider-side outcome (a refused key, a timeout, an unmappable
         *     route, nothing configured at all) is a ``200`` with ``ok: false`` and a
         *     human-readable ``detail``; only a structurally invalid request is a
         *     ``422``. Nothing here is persisted: testing an unsaved form must not
         *     change the saved configuration.
         */
        post: operations["test_connection_api_settings_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/{graph_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Graph
         * @description 404 (naming the expected, never-created path) when the graph has
         *     no compiled project yet. This route does not itself validate that a
         *     GRAPH document with this id exists -- only that a PROJECT directory
         *     does -- because ``project_exists``/``project_dir`` already validate
         *     ``graph_id`` as a path segment on their own (via
         *     ``store/_ids.py``); an invalid id therefore surfaces as a 422
         *     before any filesystem check runs, never as a false 404.
         */
        get: operations["export_graph_api_graphs__graph_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Compile
         * @description Start one compile job for a saved graph and return its id.
         *
         *     The job is registered (which enforces one live compile per graph) and
         *     its coroutine is scheduled as an asyncio task; this handler never
         *     awaits the compile, so the response returns as soon as the work is
         *     scheduled.
         *
         *     ``job.task`` is assigned before returning, and that assignment is
         *     load-bearing rather than bookkeeping: without it
         *     :meth:`~swarm_builder.compile.jobs.JobRegistry.cancel` has no task to
         *     cancel and the shutdown hook has nothing to await, so a ``DELETE``
         *     would mark the job cancelled while the pipeline kept running.
         *
         *     The project directory is deliberately never created or cleared here.
         *     ``pipeline.run_compile`` clears a stale one itself, *after* Phase 1
         *     passes, which is what keeps the "a Phase-1 refusal leaves no project
         *     directory behind" invariant true.
         *
         *     Raises:
         *         HTTPException: 404 if no such graph is saved; 422 for a
         *             malformed/path-unsafe graph id or an unreadable graph file;
         *             409 if a live compile already exists for this graph; 500 for
         *             a filesystem failure while reading the graph; 503 if the
         *             compile subsystem cannot be imported.
         */
        post: operations["start_compile_api_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compile/{compile_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compile Events
         * @description Stream one compile's events as SSE until it finishes.
         *
         *     A reconnecting client sends ``Last-Event-ID`` and gets every retained
         *     event strictly after that id, then live events. The response is
         *     deliberately *finite*: it ends after the compile's terminal
         *     ``done``/``error`` event, so a client's fetch reader completes
         *     instead of hanging on a stream that will never produce another frame.
         *
         *     Raises:
         *         HTTPException: 404 for an unknown (or evicted) ``compile_id``;
         *             400 when ``Last-Event-ID`` is not an integer, or when it
         *             predates the retained log (the body then carries the gap
         *             details and a snapshot URL); 503 if the compile subsystem
         *             cannot be imported.
         */
        get: operations["compile_events_api_compile__compile_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compile/{compile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compile Status
         * @description Return a compile's status snapshot.
         *
         *     This is the path a fresh tab uses: it has no ``Last-Event-ID`` and no
         *     way to reconstruct history, so the snapshot gives it the current
         *     status, the latest retained event id (which it can then use as a
         *     cursor), and the terminal result or error.
         *
         *     Raises:
         *         HTTPException: 404 for an unknown (or evicted) ``compile_id``;
         *             503 if the compile subsystem cannot be imported.
         */
        get: operations["compile_status_api_compile__compile_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Compile
         * @description Cancel a live compile.
         *
         *     There is no subprocess to kill (PLAN.md fact 26): a compile is one
         *     asyncio task, so cancelling that task IS the whole mechanism, and the
         *     job ends ``cancelled``.
         *
         *     **A job that already finished is a 409, not a no-op 200.** The
         *     request asks for a transition that is no longer possible and cannot
         *     be retried into success, so the honest answer is a conflict naming
         *     the status the job actually reached -- with the full snapshot in the
         *     body, so the client needs no second request to learn the outcome it
         *     was too late to prevent.
         *
         *     Raises:
         *         HTTPException: 404 for an unknown (or evicted) ``compile_id``;
         *             409 if the job is no longer live; 503 if the compile
         *             subsystem cannot be imported.
         */
        delete: operations["cancel_compile_api_compile__compile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/{graph_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs Route
         * @description Persisted runs for a graph, newest first (at most 20 are kept).
         */
        get: operations["list_runs_route_api_graphs__graph_id__runs_get"];
        put?: never;
        /**
         * Start Run
         * @description Start one run and return its job id.
         *
         *     The input is coerced up front so a bad input is a 422 here rather
         *     than a failed job. Staleness is checked here too, so the response can
         *     say whether a compile will precede the run.
         */
        post: operations["start_run_api_graphs__graph_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/{graph_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Route
         * @description One persisted run record (the live view is the job snapshot).
         */
        get: operations["get_run_route_api_graphs__graph_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/generate/clarify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clarify Graph Route
         * @description Decide whether ``body.description`` needs questions before drafting.
         *
         *     Raises:
         *         HTTPException: 422 when an attachment id is unknown or expired; 502/503
         *             for model setup and upstream failures, mirroring ``/generate``.
         */
        post: operations["clarify_graph_route_api_graphs_generate_clarify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Graph Route
         * @description Generate, save, and return a graph for ``body.description``.
         *
         *     Raises:
         *         HTTPException: 422 when every attempt failed (the detail carries the
         *             last review findings as ``problems``) or an attachment expired; 413
         *             when the attachments exceed the size cap; 503 when the resolved
         *             route is unmappable, no model is configured, or the generator
         *             cannot be imported; 500 when the graph cannot be saved.
         */
        post: operations["generate_graph_route_api_graphs_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/generate/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Graph Stream Route
         * @description ``/graphs/generate``, reporting each draft and review as it happens.
         *
         *     Everything that can be refused up front (the model route, the attachments)
         *     still fails with a plain HTTP status; only failures once drafting has begun
         *     arrive in-band, because by then the 200 is committed.
         *
         *     Raises:
         *         HTTPException: The same pre-flight statuses as ``/graphs/generate``.
         */
        post: operations["generate_graph_stream_route_api_graphs_generate_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Attachment Route
         * @description Store one uploaded file and return its id and a preview of what was read.
         *
         *     Raises:
         *         HTTPException: 413 for an oversized body, 415 for an unsupported type,
         *             422 for an unreadable file or an image under a non-vision model, 503
         *             when the parsers are missing or no model is configured (images only).
         */
        post: operations["upload_attachment_route_api_graphs_attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Attachment Route
         * @description Discard one attachment (idempotent for the caller, 404 when unknown).
         *
         *     Raises:
         *         HTTPException: 404 when the id is malformed, unknown, or already gone.
         */
        delete: operations["delete_attachment_route_api_graphs_attachments__attachmentId__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentSpec
         * @description Present on ``kind="agent"`` nodes: instructions, tools, delegation,
         *     and optional structured output for the generated agent factory.
         *
         *     ``output_schema`` is a JSON Schema object. Its values are typed as
         *     ``object`` rather than ``Any``: the *values* are arbitrary, but the
         *     container is not, and ``Any`` would also silently accept a list or a
         *     scalar where a schema object was meant.
         */
        AgentSpec: {
            /** Instructions */
            instructions: string;
            /** Tools */
            tools?: string[];
            /** Delegatesto */
            delegatesTo?: string[];
            /** Outputschema */
            outputSchema?: {
                [key: string]: unknown;
            } | null;
        };
        /** AttachmentDeleteResponse */
        AttachmentDeleteResponse: {
            /** Attachmentid */
            attachmentId: string;
            /** Deleted */
            deleted: boolean;
        };
        /**
         * AttachmentOut
         * @description One attachment, as the panel needs it.
         */
        AttachmentOut: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "csv" | "xlsx" | "pptx" | "image";
            /** Mediatype */
            mediaType: string;
            /** Bytes */
            bytes: number;
            /** Chars */
            chars: number;
            /** Truncated */
            truncated: boolean;
            /** Notes */
            notes: string[];
            /** Preview */
            preview: string;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
        };
        /**
         * AttachmentSummaryOut
         * @description One attachment as it was used by a generation.
         */
        AttachmentSummaryOut: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "csv" | "xlsx" | "pptx" | "image";
            /** Chars */
            chars: number;
            /** Truncated */
            truncated: boolean;
            /** Notes */
            notes: string[];
        };
        /** AttachmentUploadResponse */
        AttachmentUploadResponse: {
            attachment: components["schemas"]["AttachmentOut"];
            /** Warnings */
            warnings: string[];
        };
        /** Body_upload_attachment_route_api_graphs_attachments_post */
        Body_upload_attachment_route_api_graphs_attachments_post: {
            /** File */
            file: string;
        };
        /**
         * BranchEdge
         * @description One arm of a decision's dispatch, drawn on the canvas from the
         *     ``decision`` node to a branch target. ``match`` must correspond to
         *     one entry in the decision node's :class:`DecisionSpec.branches`.
         */
        BranchEdge: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "branch";
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Match */
            match: string;
        };
        /**
         * ClarifyAnswerInRaw
         * @description One answer from the panel.
         */
        ClarifyAnswerInRaw: {
            /** Questionid */
            questionId: string;
            /** Question */
            question?: string | null;
            /** Answer */
            answer: string;
        };
        /** ClarifyOptionOut */
        ClarifyOptionOut: {
            /** Label */
            label: string;
            /** Description */
            description?: string | null;
        };
        /** ClarifyQuestionOut */
        ClarifyQuestionOut: {
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Why */
            why: string;
            /** Options */
            options: components["schemas"]["ClarifyOptionOut"][];
            /** Recommended */
            recommended: string;
        };
        /**
         * ClarifyRequest
         * @description Body of ``POST /api/graphs/generate/clarify``.
         *
         *     No ``modelOverride``: the analysis pass uses the same resolved route as the
         *     draft, so model selection happens in exactly one place for this flow.
         */
        ClarifyRequest: {
            /** Description */
            description: string;
            /** Attachmentids */
            attachmentIds?: string[];
        };
        /** ClarifyResponse */
        ClarifyResponse: {
            /** Needsclarification */
            needsClarification: boolean;
            /** Questions */
            questions: components["schemas"]["ClarifyQuestionOut"][];
            /** Assumptions */
            assumptions: string[];
            /** Understanding */
            understanding: string;
            model: components["schemas"]["GenerateModelOut"];
            /** Dryrun */
            dryRun: boolean;
        };
        /**
         * CompileSnapshotResponse
         * @description Body of ``GET``/``DELETE /api/compile/{compile_id}``.
         *
         *     Mirrors :meth:`~swarm_builder.compile.jobs.Job.snapshot`'s dict
         *     one-for-one, including ``latestEventId`` -- the value a fresh client
         *     passes back as ``Last-Event-ID`` when it wants to resume rather than
         *     replay from the start.
         */
        CompileSnapshotResponse: {
            /** Compileid */
            compileId: string;
            /** Graphid */
            graphId: string;
            /**
             * Kind
             * @default compile
             * @enum {string}
             */
            kind: "compile" | "run";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** Createdat */
            createdAt: string;
            /** Startedat */
            startedAt: string | null;
            /** Finishedat */
            finishedAt: string | null;
            /** Latesteventid */
            latestEventId: number | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
        };
        /**
         * DatabaseStarterOut
         * @description One database kind's picker-facing entry.
         *
         *     ``spec`` and ``io`` are the whole reason this route exists: a new node
         *     copies both into the graph document, so the document is self-contained
         *     and the Inspector shows what will actually run (nothing is substituted at
         *     scaffold time). ``spec`` is the union of the three spec models, and it is
         *     the kind's *validated* model on the server side -- a malformed
         *     ``starter.json`` fails while the catalog is being read, never inside a
         *     generated project.
         *
         *     The scaffolding-only fields of the catalog entry (``package_module``,
         *     ``live_extra_deps``, ``manifest``) are deliberately not exposed:
         *     ``liveExtra`` names the extra a user must install and ``envVars`` lists
         *     the variables the live engine reads, which is everything the canvas can
         *     honestly tell a user. ``SWARM_DB_MODE`` is app-wide rather than an
         *     engine's, so it is not part of any entry's ``envVars``.
         */
        DatabaseStarterOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "sql" | "nosql" | "vector";
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Spec */
            spec: components["schemas"]["SqlSpec"] | components["schemas"]["NosqlSpec"] | components["schemas"]["VectorSpec"];
            io: components["schemas"]["NodeIo"];
            /** Liveextra */
            liveExtra: string;
            /** Envvars */
            envVars: string[];
        };
        /**
         * DecisionBranch
         * @description One branch of a :class:`DecisionSpec`: a match value and the node
         *     it dispatches to. ``target_node_id`` must also be the target of a
         *     ``branch`` :class:`SwarmEdge` with a matching ``match`` string.
         */
        DecisionBranch: {
            /** Match */
            match: string;
            /** Targetnodeid */
            targetNodeId: string;
        };
        /**
         * DecisionSpec
         * @description Present on ``kind="decision"`` nodes: the branch dispatch table.
         *
         *     **Data does not pass through a decision node.** A branch
         *     target step receives, via ``ctx.inputs``, the *match value returned
         *     by the decision's source step* -- not the payload that flowed into
         *     that source step. Concretely: if the source step returns
         *     ``Literal["big", "small"]``, the ``big`` branch target observes
         *     ``ctx.inputs == "big"``, never the original pre-classification
         *     string. Two consequences that hold regardless of what Phase 1 (Group
         *     2's review.py) enforces mechanically:
         *
         *     - a branch target's declared :class:`NodeIo.input_type` must equal
         *       the **decision's source step's** ``output_type``, never any node
         *       further upstream;
         *     - a workflow that needs the pre-classification payload inside a
         *       branch target must carry it through ``State`` explicitly (the
         *       classifying step writes a state field the branch target reads);
         *       ``ctx.inputs`` will never carry it through the decision.
         *
         *     Two consequences for the emitted code, both enforced elsewhere: the
         *     full ``.branch(...)`` chain must be emitted before the ``add_edge``
         *     that targets this decision (``emit_graph.py``), and branch targets'
         *     declared input types must match the source step's output type, not any
         *     node further upstream (``review.py``).
         */
        DecisionSpec: {
            /** Branches */
            branches?: components["schemas"]["DecisionBranch"][];
            /** Note */
            note?: string | null;
        };
        /**
         * DelegateEdge
         * @description A delegation link from an orchestrator node to a child agent node.
         *
         *     **Never emitted as an ``add_edge``.** The child is called as an agent
         *     *tool*, not executed as a graph step; emitting a real edge would run it
         *     twice. This edge kind exists purely so the canvas can draw the
         *     relationship and the Inspector can show it: ``emit_graph.py`` skips
         *     every ``delegate`` edge, and Phase 1 rejects a node that is both a
         *     ``delegate`` target and a ``seq``/``branch`` target.
         */
        DelegateEdge: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "delegate";
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /**
         * DeleteGraphResponse
         * @description The outcome of a delete, including whether a project was removed too.
         */
        DeleteGraphResponse: {
            /** Deleted */
            deleted: boolean;
            /** Projectdeleted */
            projectDeleted: boolean;
        };
        /**
         * ExportResponse
         * @description Where the compiled project lives and how to run it.
         */
        ExportResponse: {
            /** Projectpath */
            projectPath: string;
            /** Runcommand */
            runCommand: string;
            /**
             * Target
             * @default pydantic-graph
             * @enum {string}
             */
            target: "pydantic-graph" | "langgraph";
        };
        /**
         * FanoutEdge
         * @description One arm of a multi-successor fan-out.
         *
         *     ``join_node_id`` names the ``join`` node this arm must converge on.
         *     It is required rather than optional because a plain multi-successor
         *     ``add_edge`` pair is silently lossy: ``build()`` accepts it, and only
         *     one arbitrary branch's value survives without an explicit join.
         */
        FanoutEdge: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "fanout";
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Joinnodeid */
            joinNodeId: string;
        };
        /**
         * FindingOut
         * @description One review finding, as the canvas Inspector displays it.
         */
        FindingOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Nodeids */
            nodeIds: string[];
        };
        /**
         * GenerateGraphRequest
         * @description Body of ``POST /api/graphs/generate``.
         */
        GenerateGraphRequest: {
            /** Description */
            description: string;
            /** Name */
            name?: string | null;
            /**
             * Graphid
             * @description Reuse an existing graph id (replace its document); default mints a new one.
             */
            graphId?: string | null;
            modelOverride?: components["schemas"]["ModelSelection"] | null;
            /**
             * Attachmentids
             * @description Ids returned by POST /api/graphs/attachments. The count and total-size caps are enforced by the store, which reports them as a 413 with code attachment_too_large -- not as a schema-validation error.
             */
            attachmentIds?: string[];
            /**
             * Answers
             * @description Answers to the clarify pass' questions; authoritative for the draft.
             */
            answers?: components["schemas"]["ClarifyAnswerInRaw"][];
        };
        /** GenerateGraphResponse */
        GenerateGraphResponse: {
            graph: components["schemas"]["SwarmGraph"];
            /** Warnings */
            warnings: components["schemas"]["FindingOut"][];
            /** Attempts */
            attempts: number;
            model: components["schemas"]["GenerateModelOut"];
            /** Dryrun */
            dryRun: boolean;
            /** Attachments */
            attachments?: components["schemas"]["AttachmentSummaryOut"][];
        };
        /** GenerateModelOut */
        GenerateModelOut: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Source */
            source: string;
        };
        /**
         * GraphListError
         * @description A graph file that exists on disk but could not be read or validated.
         *
         *     Reported alongside the valid rows rather than replacing them, so one
         *     corrupt file never hides every other saved graph.
         */
        GraphListError: {
            /** Id */
            id: string;
            /** Detail */
            detail: string;
        };
        /**
         * GraphListResponse
         * @description The full ``GET /api/graphs`` response body.
         *
         *     ``errors`` is non-empty only when individual files failed; the request
         *     itself still succeeded.
         */
        GraphListResponse: {
            /** Graphs */
            graphs: components["schemas"]["GraphSummary"][];
            /** Errors */
            errors: components["schemas"]["GraphListError"][];
        };
        /**
         * GraphSummary
         * @description One row of the graph list: enough for a picker, none of the document.
         */
        GraphSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Nodecount */
            nodeCount: number;
            /** Edgecount */
            edgeCount: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description The full ``GET /api/health`` response body.
         */
        HealthResponse: {
            /** Version */
            version: string;
            /** Dshhome */
            dshHome: string;
            /** Settingserror */
            settingsError: string | null;
            resolvedModel: components["schemas"]["ResolvedModelSummary"];
            /** Uvavailable */
            uvAvailable: boolean;
            /** Uvcachedir */
            uvCacheDir: string;
            /** Uvcachewritable */
            uvCacheWritable: boolean;
            /** Workspacedir */
            workspaceDir: string;
            /** Workspacewritable */
            workspaceWritable: boolean;
            /** Webdistpresent */
            webDistPresent: boolean;
            /** Compileready */
            compileReady: boolean;
            /** Blockers */
            blockers: string[];
            /** Runready */
            runReady: boolean;
            /** Runblockers */
            runBlockers: string[];
            /** Dryrun */
            dryRun: boolean;
            /** Dryrunforcedbyenv */
            dryRunForcedByEnv: boolean;
            /** Modelconfigured */
            modelConfigured: boolean;
            /** Appconfigpath */
            appConfigPath: string;
            /** Appconfigerror */
            appConfigError: string | null;
        };
        /**
         * JoinEdge
         * @description An edge from a fan-out arm's target into the ``join`` node.
         */
        JoinEdge: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "join";
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /**
         * JoinSpec
         * @description Present on ``kind="join"`` nodes: the fan-in reducer.
         *
         *     ``initial_factory`` names the Python builtin the emitter passes as
         *     ``builder.join(..., initial_factory=...)``. When unset, the emitter
         *     derives it from ``reducer`` (``list_append``/``list_extend`` ->
         *     ``list``, ``dict_update`` -> ``dict``, ``sum`` -> ``int``); set it
         *     explicitly only to override that default.
         */
        JoinSpec: {
            /**
             * Reducer
             * @enum {string}
             */
            reducer: "list_append" | "list_extend" | "dict_update" | "sum";
            /** Initialfactory */
            initialFactory?: ("list" | "dict" | "int") | null;
        };
        /**
         * ModelInfoOut
         * @description One entry of a route's explicit model list, as the picker sees it.
         */
        ModelInfoOut: {
            /** Id */
            id: string;
            /** Name */
            name: string | null;
        };
        /**
         * ModelInput
         * @description One provider/model/key submission.
         *
         *     An omitted ``api_key`` keeps the stored key when the provider is
         *     unchanged; ``clear_api_key`` removes it; a non-empty ``api_key`` replaces
         *     it (:func:`swarm_builder.appconfig.apply_update`).
         */
        ModelInput: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Baseurl */
            baseUrl?: string | null;
            /** Apikey */
            apiKey?: string | null;
            /** Clearapikey */
            clearApiKey?: boolean | null;
            /** Reasoningeffort */
            reasoningEffort?: string | null;
            /** Maxtokens */
            maxTokens?: number | null;
        };
        /**
         * ModelSelection
         * @description One inherited route, resolved to something PydanticAI can
         *     construct (facts 21-24). Absent on :class:`SwarmGraph` means
         *     "inherit the resolved default" rather than "no model".
         */
        ModelSelection: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Reasoningeffort */
            reasoningEffort?: string | null;
        };
        /**
         * ModelsResponse
         * @description The full ``GET /api/models`` response body.
         *
         *     ``app_route`` is the route configured in Swarm Builder's *own* model
         *     settings, classified exactly like an inherited one, so a picker can list
         *     it first with the same enable/disable treatment. It is reported
         *     separately from ``routes`` rather than merged into it because the two
         *     have different lifetimes: a harness route exists because someone edited a
         *     machine-wide file, while this one exists because the user configured it
         *     in this application.
         */
        ModelsResponse: {
            /** Routes */
            routes: components["schemas"]["RouteOut"][];
            appRoute: components["schemas"]["RouteOut"] | null;
            resolvedDefault: components["schemas"]["ResolvedDefaultOut"];
            /** Settingserror */
            settingsError: string | null;
        };
        /**
         * NodeIo
         * @description A node's declared input/output port types.
         *
         *     Phase 1 review uses these to reject a port-type mismatch across an
         *     edge and, for a decision's branch targets, to enforce that the
         *     target's ``input_type`` equals the decision's *source step's*
         *     ``output_type`` -- see :class:`DecisionSpec` for why the source step is
         *     the relevant node rather than the decision itself.
         */
        NodeIo: {
            /**
             * Inputtype
             * @enum {string}
             */
            inputType: "str" | "json" | "list[str]" | "list[json]";
            /**
             * Outputtype
             * @enum {string}
             */
            outputType: "str" | "json" | "list[str]" | "list[json]";
        };
        /**
         * NodeRunRecord
         * @description What one step reported during a run (the last ``node`` frame wins).
         */
        NodeRunRecord: {
            /** Status */
            status: string;
            /** Inputs */
            inputs?: unknown | null;
            /** Output */
            output?: unknown | null;
            /** Statedelta */
            stateDelta?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Durationms */
            durationMs?: number | null;
        };
        /**
         * NosqlSpec
         * @description Present on ``kind="nosql"`` nodes: one collection, one operation.
         *
         *     ``filter`` values may be the sentinel string ``"$input"``, which the
         *     emitter replaces with the upstream node's value -- so the document can
         *     say "match the field the user's input names" without carrying any
         *     expression language into a JSON document. ``limit`` is a warning
         *     threshold rather than a hard rule (``<= 0`` reads as "unbounded"), so a
         *     deliberate full scan stays expressible.
         */
        NosqlSpec: {
            /** Collection */
            collection: string;
            /**
             * Operation
             * @default find
             * @enum {string}
             */
            operation: "find" | "find_one" | "count" | "insert_one";
            /** Filter */
            filter?: {
                [key: string]: unknown;
            };
            /**
             * Limit
             * @default 20
             */
            limit: number;
            /** Seed */
            seed?: {
                [key: string]: unknown;
            }[];
            /** Note */
            note?: string | null;
        };
        /**
         * Position
         * @description Canvas coordinates for a node. Presentation-only: never read by
         *     the emitter, kept purely so the canvas restores node placement.
         */
        Position: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * ProgrammaticSpec
         * @description Present on ``kind="programmatic"`` nodes: plain-Python steps with
         *     no agent. ``needs`` are extra package requirements the scaffolder
         *     unions into the generated ``pyproject.toml``; ``signature_hint`` is
         *     free-text guidance the fill agent reads (never executed or parsed).
         */
        ProgrammaticSpec: {
            /** Needs */
            needs?: string[];
            /** Signaturehint */
            signatureHint?: string | null;
        };
        /**
         * ProviderOut
         * @description One entry of the provider catalog the settings screen renders.
         */
        ProviderOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Requiresapikey */
            requiresApiKey: boolean;
            /** Requiresbaseurl */
            requiresBaseUrl: boolean;
            /** Apikeyenv */
            apiKeyEnv: string | null;
            /** Defaultmodel */
            defaultModel: string | null;
            /** Models */
            models: string[];
            /** Note */
            note: string | null;
            /** Usable */
            usable: boolean;
            /** Unusablereason */
            unusableReason: string | null;
        };
        /**
         * ResolvedDefaultOut
         * @description The model a compile would use right now, plus where that came from.
         */
        ResolvedDefaultOut: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Source */
            source: string;
        };
        /**
         * ResolvedModelSummary
         * @description The subset of :class:`~swarm_builder.inherit.settings.EffectiveModel`
         *     that is meaningful to a health check. ``reasoning_effort``,
         *     ``base_url``, ``api_key_env``, and ``route`` are internal resolution
         *     detail and are intentionally dropped here (the picker-facing detail
         *     lives in ``/api/models`` instead).
         */
        ResolvedModelSummary: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Source */
            source: string;
        };
        /**
         * ReviewResponse
         * @description The Phase-1 review outcome: a pass/fail flag plus every finding.
         */
        ReviewResponse: {
            /** Ok */
            ok: boolean;
            /** Errors */
            errors: components["schemas"]["FindingOut"][];
            /** Warnings */
            warnings: components["schemas"]["FindingOut"][];
        };
        /**
         * RouteOut
         * @description One configured route, with the picker-relevant classification fields.
         *
         *     ``emission``/``required_extra``/``unmappable_reason`` are the outcome
         *     of :func:`swarm_builder.inherit.routes.classify_route`, exposed so the
         *     picker can disable or explain an unusable route before a compile is
         *     attempted.
         */
        RouteOut: {
            /** Key */
            key: string;
            /** Api */
            api: string | null;
            /** Hasexplicitmodels */
            hasExplicitModels: boolean;
            /** Emission */
            emission: string;
            /** Requiredextra */
            requiredExtra: string | null;
            /** Unmappablereason */
            unmappableReason: string | null;
            /** Models */
            models: components["schemas"]["ModelInfoOut"][];
        };
        /** RunListResponse */
        RunListResponse: {
            /** Runs */
            runs: components["schemas"]["RunRecord"][];
        };
        /**
         * RunRecord
         * @description One persisted run.
         */
        RunRecord: {
            /** Runid */
            runId: string;
            /** Graphid */
            graphId: string;
            /** Status */
            status: string;
            /** Createdat */
            createdAt: string;
            /** Finishedat */
            finishedAt?: string | null;
            /** Input */
            input?: unknown | null;
            /** Output */
            output?: unknown | null;
            /** State */
            state?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Model */
            model?: string | null;
            /** Durationms */
            durationMs?: number | null;
            /**
             * Compiled
             * @default false
             */
            compiled: boolean;
            /**
             * Dryrun
             * @default false
             */
            dryRun: boolean;
            /** Nodes */
            nodes?: {
                [key: string]: components["schemas"]["NodeRunRecord"];
            };
        };
        /**
         * SavedModelOut
         * @description The saved model, minus the secret.
         *
         *     ``api_key_hint`` is the last four characters of the stored key -- enough
         *     for a user to tell two keys apart, not enough to use one. The value itself
         *     is never part of any response body.
         */
        SavedModelOut: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Baseurl */
            baseUrl: string | null;
            /** Reasoningeffort */
            reasoningEffort: string | null;
            /** Maxtokens */
            maxTokens: number | null;
            /** Hasapikey */
            hasApiKey: boolean;
            /** Apikeyhint */
            apiKeyHint: string | null;
        };
        /**
         * SeqEdge
         * @description A plain sequential edge: ``builder.add_edge(source, target)``.
         */
        SeqEdge: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "seq";
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Label */
            label?: string | null;
        };
        /**
         * SettingsResponse
         * @description The full ``GET /api/settings`` body.
         */
        SettingsResponse: {
            /** Configpath */
            configPath: string;
            /** Configerror */
            configError: string | null;
            model: components["schemas"]["SavedModelOut"] | null;
            /** Dryrun */
            dryRun: boolean;
            /** Dryrunforcedbyenv */
            dryRunForcedByEnv: boolean;
            /** Dryrunenvvars */
            dryRunEnvVars: string[];
            /** Providers */
            providers: components["schemas"]["ProviderOut"][];
            resolvedDefault: components["schemas"]["ResolvedDefaultOut"];
            /** Maxtokensdefault */
            maxTokensDefault: number;
            /** Inheritedroutes */
            inheritedRoutes: number;
            /** Workspacewritable */
            workspaceWritable: boolean;
        };
        /**
         * SettingsUpdateRequest
         * @description Body of ``PUT /api/settings``.
         *
         *     ``None`` means "leave this alone", which is what lets the dry-run switch be
         *     toggled without resubmitting the model form (and vice versa). Removing the
         *     in-app model entirely is the explicit ``clear_model`` flag rather than an
         *     ambiguous ``model: null``.
         */
        SettingsUpdateRequest: {
            model?: components["schemas"]["ModelInput"] | null;
            /** Dryrun */
            dryRun?: boolean | null;
            /** Clearmodel */
            clearModel?: boolean | null;
        };
        /**
         * SqlSpec
         * @description Present on ``kind="sql"`` nodes. ``query`` uses ``:name`` placeholders
         *     (``sqlite3``'s native form -- the live adapter rewrites them for the
         *     driver, and one declaration syntax keeps the Inspector honest about
         *     which parameters the query actually binds).
         *
         *     The split between ``query`` and ``seed_sql`` is deliberate: a node's
         *     declared operation is what the step and any agent tool run, while the
         *     seed is the mock's schema *and* rows. ``write`` is a declaration, not a
         *     hint -- it selects the emitted call (``execute()`` instead of
         *     ``query()``) and disqualifies the node as an agent tool, because a
         *     write reachable from a model's tool call is exactly the injection
         *     surface this design refuses to create.
         */
        SqlSpec: {
            /** Query */
            query: string;
            /** Seedsql */
            seedSql: string;
            /**
             * Write
             * @default false
             */
            write: boolean;
            /** Note */
            note?: string | null;
        };
        /**
         * StartCompileRequest
         * @description Body of ``POST /api/compile``.
         *
         *     ``target`` selects the export: ``pydantic-graph`` (default, the five
         *     phases) or ``langgraph`` (the five phases, then a conversion of the
         *     validated project into a LangGraph export under
         *     ``workspace/projects-langgraph/<name-slug>/``).
         */
        StartCompileRequest: {
            /** Graphid */
            graphId: string;
            /**
             * Target
             * @default pydantic-graph
             * @enum {string}
             */
            target: "pydantic-graph" | "langgraph";
        };
        /**
         * StartCompileResponse
         * @description Body of a successful ``POST /api/compile``.
         *
         *     Only the id: the compile itself runs in the background and reports
         *     everything else through the event stream and the status snapshot.
         */
        StartCompileResponse: {
            /** Compileid */
            compileId: string;
        };
        /**
         * StartRunRequest
         * @description Body of ``POST /api/graphs/:id/runs``.
         *
         *     ``input`` is interpreted by the entry node's ``inputType``
         *     (``compile/run.py``'s ``coerce_input``): a ``str`` port takes the
         *     string verbatim; ``json``/``list[str]`` take the parsed value or a
         *     JSON string of it. ``compileIfStale`` (default on) recompiles a
         *     missing or out-of-date project before running; off, a stale project
         *     is a 409.
         */
        StartRunRequest: {
            /** Input */
            input: unknown;
            /**
             * Compileifstale
             * @default true
             */
            compileIfStale: boolean;
        };
        /** StartRunResponse */
        StartRunResponse: {
            /** Runid */
            runId: string;
            /** Willcompile */
            willCompile: boolean;
            /** Dryrun */
            dryRun: boolean;
        };
        /**
         * StateField
         * @description One field of the generated workflow's ``@dataclass State``.
         *
         *     ``type`` goes through :data:`PORT_TYPE_ANNOTATIONS` like any other
         *     port type when the emitter writes the dataclass field.
         *     ``default`` is literal Python source for the field's default value
         *     (e.g. ``'""'`` or ``"0"``); ``None`` means the emitter writes a bare
         *     ``name: type`` line with no default.
         */
        StateField: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "str" | "json" | "list[str]" | "list[json]";
            /** Default */
            default?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * SwarmGraph
         * @description The complete canvas save file: nodes, edges, state shape, and the
         *     optional per-workflow model override. ``version`` is fixed at ``1``
         *     for this schema generation; a future incompatible shape change ships
         *     as ``version=2`` plus a migration, not a silent field rename.
         */
        SwarmGraph: {
            /**
             * Version
             * @default 1
             * @constant
             */
            version: 1;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Entrynodeid */
            entryNodeId: string;
            /** Exitnodeid */
            exitNodeId: string;
            /** Statefields */
            stateFields?: components["schemas"]["StateField"][];
            /** Nodes */
            nodes?: components["schemas"]["SwarmNode"][];
            /** Edges */
            edges?: (components["schemas"]["SeqEdge"] | components["schemas"]["BranchEdge"] | components["schemas"]["FanoutEdge"] | components["schemas"]["JoinEdge"] | components["schemas"]["DelegateEdge"])[];
            model?: components["schemas"]["ModelSelection"] | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * SwarmNode
         * @description One canvas node.
         *
         *     ``id`` is emitted verbatim as the ``node_id=`` argument to
         *     ``builder.step``/``builder.decision``/``builder.join`` and as the step
         *     module's filename, so it must already be a valid, unique Python
         *     identifier. The frontend is responsible for deriving it from ``title``
         *     via :func:`swarm_builder.slugify.slugify_titles` and keeping it stable
         *     across edits: duplicate titles deduplicate with a numeric suffix, and
         *     the title-to-id mapping must stay stable across recompiles or a
         *     recompile would rename step modules instead of updating them.
         *
         *     Exactly one of ``agent`` / ``programmatic`` / ``decision`` / ``join`` /
         *     ``sql`` / ``nosql`` / ``vector`` is expected to be set, matching
         *     ``kind`` -- enforced by Phase 1 (``review.py``), not here, since that
         *     cross-field rule belongs with the rest of the structural graph
         *     validation. A database node's ``io`` pair is likewise fixed by its
         *     kind (``str -> list[json]``), and it never carries a ``template``:
         *     templates are agent-only, and a stale value there would be silently
         *     ignored.
         */
        SwarmNode: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "agent" | "programmatic" | "decision" | "join" | "sql" | "nosql" | "vector";
            /** Title */
            title: string;
            /** Intent */
            intent: string;
            position: components["schemas"]["Position"];
            /** Template */
            template?: ("chat" | "orchestrator" | "websearch") | null;
            io: components["schemas"]["NodeIo"];
            /** Reads */
            reads?: string[];
            /** Writes */
            writes?: string[];
            agent?: components["schemas"]["AgentSpec"] | null;
            programmatic?: components["schemas"]["ProgrammaticSpec"] | null;
            decision?: components["schemas"]["DecisionSpec"] | null;
            join?: components["schemas"]["JoinSpec"] | null;
            sql?: components["schemas"]["SqlSpec"] | null;
            nosql?: components["schemas"]["NosqlSpec"] | null;
            vector?: components["schemas"]["VectorSpec"] | null;
        };
        /**
         * TemplateEntryOut
         * @description The five picker-facing fields of one template catalog entry.
         *
         *     ``deps`` and ``file_manifest`` are internal scaffolding concerns the
         *     picker has no use for, so they are deliberately not exposed.
         */
        TemplateEntryOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Defaulttools */
            defaultTools: string[];
            /** Requiredenv */
            requiredEnv: string[];
        };
        /**
         * TestConnectionRequest
         * @description Body of ``POST /api/settings/test`` -- all fields optional.
         *
         *     Anything omitted falls back to the saved configuration, so the common
         *     case (``{}``) tests exactly what a compile would use. Supplying fields is
         *     how the screen tests an unsaved form.
         */
        TestConnectionRequest: {
            /** Provider */
            provider?: string | null;
            /** Model */
            model?: string | null;
            /** Baseurl */
            baseUrl?: string | null;
            /** Apikey */
            apiKey?: string | null;
        };
        /**
         * TestConnectionResponse
         * @description The result of one test call.
         *
         *     A provider refusing the key, timing out, or being unreachable are all
         *     *results*, not HTTP errors: the screen shows the detail inline next to the
         *     form the user needs to fix.
         */
        TestConnectionResponse: {
            /** Ok */
            ok: boolean;
            /** Detail */
            detail: string;
            /** Latencyms */
            latencyMs: number | null;
            /** Model */
            model: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VectorDocument
         * @description One seeded vector document. ``metadata`` stays a plain dict rather
         *     than a per-node schema: the mock never filters on it, and a live
         *     collection's payload shape is the user's business, not the canvas's.
         */
        VectorDocument: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * VectorSpec
         * @description Present on ``kind="vector"`` nodes: a collection and a seed index.
         *
         *     ``min_score`` is cosine similarity in ``[-1, 1]``, so its default of
         *     ``0.0`` means "no threshold" rather than "no weak matches" -- a
         *     threshold that admitted nothing by default would make a freshly created
         *     node return an empty list and look broken.
         */
        VectorSpec: {
            /** Collection */
            collection: string;
            /**
             * Topk
             * @default 4
             */
            topK: number;
            /**
             * Minscore
             * @default 0
             */
            minScore: number;
            /** Seed */
            seed?: components["schemas"]["VectorDocument"][];
            /** Note */
            note?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_graphs_route_api_graphs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphListResponse"];
                };
            };
        };
    };
    get_graph_route_api_graphs__graph_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwarmGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_graph_route_api_graphs__graph_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwarmGraph"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwarmGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_graph_route_api_graphs__graph_id__delete: {
        parameters: {
            query?: {
                project?: boolean;
            };
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_graph_route_api_graphs__graph_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateEntryOut"][];
                };
            };
        };
    };
    list_database_starters_api_database_starters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseStarterOut"][];
                };
            };
        };
    };
    get_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    put_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description the submitted provider/model/key combination is not usable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the settings file could not be written */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    test_connection_api_settings_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_graph_api_graphs__graph_id__export_get: {
        parameters: {
            query?: {
                target?: "pydantic-graph" | "langgraph";
            };
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_compile_api_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartCompileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartCompileResponse"];
                };
            };
            /** @description no such graph */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description a compile is already live for this graph */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description the compile subsystem is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    compile_events_api_compile__compile_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description compile event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Last-Event-ID predates the retained log */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such compile job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description the compile subsystem is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    compile_status_api_compile__compile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileSnapshotResponse"];
                };
            };
            /** @description no such compile job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description the compile subsystem is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_compile_api_compile__compile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileSnapshotResponse"];
                };
            };
            /** @description no such compile job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the compile has already finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description the compile subsystem is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_runs_route_api_graphs__graph_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_graphs__graph_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunResponse"];
                };
            };
            /** @description no such graph */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description a compile or run is already live, or the project is stale */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the input does not fit the entry node's port type */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the run subsystem is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_run_route_api_graphs__graph_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description no such run record */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clarify_graph_route_api_graphs_generate_clarify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClarifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClarifyResponse"];
                };
            };
            /** @description the description or an attachment is unusable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the model API refused or failed the request, or answered unusably */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no usable route or credential, or the generator is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generate_graph_route_api_graphs_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateGraphRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateGraphResponse"];
                };
            };
            /** @description the attachments exceed the per-request size cap */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the model could not produce a review-clean graph */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the model API refused or failed the request */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no usable route or credential, or the generator is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    generate_graph_stream_route_api_graphs_generate_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateGraphRequest"];
            };
        };
        responses: {
            /** @description SSE: `progress` events (stage, attempt, maxAttempts, problems), then `saving`, then one terminal `done` (a GenerateGraphResponse) or `error` (`{status, detail}`, the status and detail /generate would have returned) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description the attachments exceed the per-request size cap */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the description or an attachment is unusable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no usable route or credential, or the generator is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    upload_attachment_route_api_graphs_attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_attachment_route_api_graphs_attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentUploadResponse"];
                };
            };
            /** @description the file exceeds the per-file size cap */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the file type is not supported */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the file could not be read, or the model cannot read images */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the attachment readers are unavailable, or no model is configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_attachment_route_api_graphs_attachments__attachmentId__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentDeleteResponse"];
                };
            };
            /** @description no such attachment */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
