/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Health
         * @description Report server version, resolved model/settings state, and
         *     whether a compile is currently expected to succeed.
         *
         *     ``compile_ready`` is ``False`` -- with a human-readable string
         *     appended to ``blockers`` for each contributing reason -- whenever
         *     any of: the resolved default model came from the bundle fallback
         *     (nothing the user actually configured); ``uv`` is not on ``PATH``;
         *     the resolved workspace directory is not writable; or
         *     ``settings.yaml`` exists but failed to parse/read. Otherwise
         *     ``compile_ready`` is ``True`` and ``blockers`` is empty.
         */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Graphs Route
         * @description List every saved graph as a summary, plus one entry per file that
         *     failed to parse/validate -- a single bad file never 500s the whole
         *     listing (``store.graphs.list_graphs``'s own contract).
         */
        get: operations["list_graphs_route_api_graphs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/{graph_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph Route
         * @description Return the full graph document.
         *
         *     404 (naming the resolved path that was checked) when no such graph
         *     exists; 422 for a malformed/path-unsafe id, or for a graph file that
         *     is not valid JSON or fails :class:`SwarmGraph` validation (a client's
         *     own bad write, or a file corrupted by an interrupted process -- never
         *     an uncaught exception reaching the ASGI stack); 500 for any other
         *     filesystem failure while reading.
         */
        get: operations["get_graph_route_api_graphs__graph_id__get"];
        /**
         * Put Graph Route
         * @description Validate + atomically write a graph document.
         *
         *     The path id is authoritative: a body ``id`` that disagrees with the
         *     path parameter is rejected with 422 naming both, rather than
         *     silently overwritten or silently accepted. ``updated_at`` is always
         *     server-stamped to ``datetime.now(UTC)`` on every successful write,
         *     overwriting whatever placeholder the client sent -- the response
         *     body reflects the stamp that was actually persisted.
         *
         *     Body validation against :class:`SwarmGraph` (including its
         *     ``_check_structural_integrity`` model validator) happens
         *     automatically via the ``graph: SwarmGraph`` parameter annotation
         *     before this function body even runs; a validation failure surfaces
         *     as FastAPI's normal 422 with no extra handling needed here.
         */
        put: operations["put_graph_route_api_graphs__graph_id__put"];
        post?: never;
        /**
         * Delete Graph Route
         * @description Remove the graph document; also remove its generated project
         *     directory when ``?project=true`` is given (idempotent -- a project
         *     that was never compiled is not an error).
         *
         *     404 when the graph itself does not exist (the ``?project`` flag
         *     never changes that: a missing graph is always a 404 regardless of
         *     whether a project directory happens to exist for that id).
         */
        delete: operations["delete_graph_route_api_graphs__graph_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/{graph_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Graph Route
         * @description Run the Phase-1 static review over a saved graph.
         *
         *     This is the "initial review" a user triggers before compiling: cycles,
         *     unreachable nodes, state ownership, port-type mismatches, branch
         *     consistency, and the rest of the structural rules.
         *
         *     **Lazy import, deliberately -- this is a degradation seam.** The whole
         *     ``swarm_builder.compile`` subsystem exists only to serve the compile
         *     and review endpoints, and it is much heavier than the rest of the
         *     server (it pulls in the codegen, agent and pipeline modules). Importing
         *     it at module level would make a broken compile subsystem take the
         *     entire server down at startup; importing it here means that subsystem
         *     fails *this endpoint* alone, with a clear 503, while graph CRUD,
         *     templates, models and health keep working.
         */
        post: operations["review_graph_route_api_graphs__graph_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description Return the template catalog's five picker-facing fields.
         *
         *     Raises:
         *         fastapi.HTTPException: 503 if the template registry cannot be
         *             imported, so one broken subsystem fails this route rather
         *             than server startup.
         */
        get: operations["list_templates_api_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Models
         * @description List every configured harness route plus the resolved default,
         *     for a model picker UI.
         *
         *     A route is only ever read from a :class:`Settings` whose ``error``
         *     is ``None`` (a settings file that failed to parse contributes zero
         *     routes, matching :func:`resolve_effective_model`'s own fallthrough
         *     behavior) -- but ``settings_error`` itself is still reported
         *     verbatim so the picker can explain why the route list is empty.
         */
        get: operations["get_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/{graph_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Graph
         * @description 404 (naming the expected, never-created path) when the graph has
         *     no compiled project yet. This route does not itself validate that a
         *     GRAPH document with this id exists -- only that a PROJECT directory
         *     does -- because ``project_exists``/``project_dir`` already validate
         *     ``graph_id`` as a path segment on their own (via
         *     ``store/_ids.py``); an invalid id therefore surfaces as a 422
         *     before any filesystem check runs, never as a false 404.
         */
        get: operations["export_graph_api_graphs__graph_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Compile
         * @description Start one compile job for a saved graph and return its id.
         *
         *     The job is registered (which enforces one live compile per graph) and
         *     its coroutine is scheduled as an asyncio task; this handler never
         *     awaits the compile, so the response returns as soon as the work is
         *     scheduled.
         *
         *     ``job.task`` is assigned before returning, and that assignment is
         *     load-bearing rather than bookkeeping: without it
         *     :meth:`~swarm_builder.compile.jobs.JobRegistry.cancel` has no task to
         *     cancel and the shutdown hook has nothing to await, so a ``DELETE``
         *     would mark the job cancelled while the pipeline kept running.
         *
         *     The project directory is deliberately never created or cleared here.
         *     ``pipeline.run_compile`` clears a stale one itself, *after* Phase 1
         *     passes, which is what keeps the "a Phase-1 refusal leaves no project
         *     directory behind" invariant true.
         *
         *     Raises:
         *         HTTPException: 404 if no such graph is saved; 422 for a
         *             malformed/path-unsafe graph id or an unreadable graph file;
         *             409 if a live compile already exists for this graph; 500 for
         *             a filesystem failure while reading the graph; 503 if the
         *             compile subsystem cannot be imported.
         */
        post: operations["start_compile_api_compile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compile/{compile_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compile Events
         * @description Stream one compile's events as SSE until it finishes.
         *
         *     A reconnecting client sends ``Last-Event-ID`` and gets every retained
         *     event strictly after that id, then live events. The response is
         *     deliberately *finite*: it ends after the compile's terminal
         *     ``done``/``error`` event, so a client's fetch reader completes
         *     instead of hanging on a stream that will never produce another frame.
         *
         *     Raises:
         *         HTTPException: 404 for an unknown (or evicted) ``compile_id``;
         *             400 when ``Last-Event-ID`` is not an integer, or when it
         *             predates the retained log (the body then carries the gap
         *             details and a snapshot URL); 503 if the compile subsystem
         *             cannot be imported.
         */
        get: operations["compile_events_api_compile__compile_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compile/{compile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compile Status
         * @description Return a compile's status snapshot.
         *
         *     This is the path a fresh tab uses: it has no ``Last-Event-ID`` and no
         *     way to reconstruct history, so the snapshot gives it the current
         *     status, the latest retained event id (which it can then use as a
         *     cursor), and the terminal result or error.
         *
         *     Raises:
         *         HTTPException: 404 for an unknown (or evicted) ``compile_id``;
         *             503 if the compile subsystem cannot be imported.
         */
        get: operations["compile_status_api_compile__compile_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Compile
         * @description Cancel a live compile.
         *
         *     There is no subprocess to kill (PLAN.md fact 26): a compile is one
         *     asyncio task, so cancelling that task IS the whole mechanism, and the
         *     job ends ``cancelled``.
         *
         *     **A job that already finished is a 409, not a no-op 200.** The
         *     request asks for a transition that is no longer possible and cannot
         *     be retried into success, so the honest answer is a conflict naming
         *     the status the job actually reached -- with the full snapshot in the
         *     body, so the client needs no second request to learn the outcome it
         *     was too late to prevent.
         *
         *     Raises:
         *         HTTPException: 404 for an unknown (or evicted) ``compile_id``;
         *             409 if the job is no longer live; 503 if the compile
         *             subsystem cannot be imported.
         */
        delete: operations["cancel_compile_api_compile__compile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/{graph_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs Route
         * @description Persisted runs for a graph, newest first (at most 20 are kept).
         */
        get: operations["list_runs_route_api_graphs__graph_id__runs_get"];
        put?: never;
        /**
         * Start Run
         * @description Start one run and return its job id.
         *
         *     The input is coerced up front so a bad input is a 422 here rather
         *     than a failed job. Staleness is checked here too, so the response can
         *     say whether a compile will precede the run.
         */
        post: operations["start_run_api_graphs__graph_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/{graph_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Route
         * @description One persisted run record (the live view is the job snapshot).
         */
        get: operations["get_run_route_api_graphs__graph_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/graphs/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Graph Route
         * @description Generate, save, and return a graph for ``body.description``.
         *
         *     Raises:
         *         HTTPException: 422 when every attempt failed (the detail carries the
         *             last review findings as ``problems``); 503 when the resolved
         *             route is unmappable, no model is configured, or the generator
         *             cannot be imported; 500 when the graph cannot be saved.
         */
        post: operations["generate_graph_route_api_graphs_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentSpec
         * @description Present on ``kind="agent"`` nodes: instructions, tools, delegation,
         *     and optional structured output for the generated agent factory.
         *
         *     ``output_schema`` is a JSON Schema object. Its values are typed as
         *     ``object`` rather than ``Any``: the *values* are arbitrary, but the
         *     container is not, and ``Any`` would also silently accept a list or a
         *     scalar where a schema object was meant.
         */
        AgentSpec: {
            /** Instructions */
            instructions: string;
            /** Tools */
            tools?: string[];
            /** Delegatesto */
            delegatesTo?: string[];
            /** Outputschema */
            outputSchema?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * BranchEdge
         * @description One arm of a decision's dispatch, drawn on the canvas from the
         *     ``decision`` node to a branch target. ``match`` must correspond to
         *     one entry in the decision node's :class:`DecisionSpec.branches`.
         */
        BranchEdge: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "branch";
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Match */
            match: string;
        };
        /**
         * CompileSnapshotResponse
         * @description Body of ``GET``/``DELETE /api/compile/{compile_id}``.
         *
         *     Mirrors :meth:`~swarm_builder.compile.jobs.Job.snapshot`'s dict
         *     one-for-one, including ``latestEventId`` -- the value a fresh client
         *     passes back as ``Last-Event-ID`` when it wants to resume rather than
         *     replay from the start.
         */
        CompileSnapshotResponse: {
            /** Compileid */
            compileId: string;
            /** Graphid */
            graphId: string;
            /**
             * Kind
             * @default compile
             * @enum {string}
             */
            kind: "compile" | "run";
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** Createdat */
            createdAt: string;
            /** Startedat */
            startedAt: string | null;
            /** Finishedat */
            finishedAt: string | null;
            /** Latesteventid */
            latestEventId: number | null;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
        };
        /**
         * DecisionBranch
         * @description One branch of a :class:`DecisionSpec`: a match value and the node
         *     it dispatches to. ``target_node_id`` must also be the target of a
         *     ``branch`` :class:`SwarmEdge` with a matching ``match`` string.
         */
        DecisionBranch: {
            /** Match */
            match: string;
            /** Targetnodeid */
            targetNodeId: string;
        };
        /**
         * DecisionSpec
         * @description Present on ``kind="decision"`` nodes: the branch dispatch table.
         *
         *     **Data does not pass through a decision node.** A branch
         *     target step receives, via ``ctx.inputs``, the *match value returned
         *     by the decision's source step* -- not the payload that flowed into
         *     that source step. Concretely: if the source step returns
         *     ``Literal["big", "small"]``, the ``big`` branch target observes
         *     ``ctx.inputs == "big"``, never the original pre-classification
         *     string. Two consequences that hold regardless of what Phase 1 (Group
         *     2's review.py) enforces mechanically:
         *
         *     - a branch target's declared :class:`NodeIo.input_type` must equal
         *       the **decision's source step's** ``output_type``, never any node
         *       further upstream;
         *     - a workflow that needs the pre-classification payload inside a
         *       branch target must carry it through ``State`` explicitly (the
         *       classifying step writes a state field the branch target reads);
         *       ``ctx.inputs`` will never carry it through the decision.
         *
         *     Two consequences for the emitted code, both enforced elsewhere: the
         *     full ``.branch(...)`` chain must be emitted before the ``add_edge``
         *     that targets this decision (``emit_graph.py``), and branch targets'
         *     declared input types must match the source step's output type, not any
         *     node further upstream (``review.py``).
         */
        DecisionSpec: {
            /** Branches */
            branches?: components["schemas"]["DecisionBranch"][];
            /** Note */
            note?: string | null;
        };
        /**
         * DelegateEdge
         * @description A delegation link from an orchestrator node to a child agent node.
         *
         *     **Never emitted as an ``add_edge``.** The child is called as an agent
         *     *tool*, not executed as a graph step; emitting a real edge would run it
         *     twice. This edge kind exists purely so the canvas can draw the
         *     relationship and the Inspector can show it: ``emit_graph.py`` skips
         *     every ``delegate`` edge, and Phase 1 rejects a node that is both a
         *     ``delegate`` target and a ``seq``/``branch`` target.
         */
        DelegateEdge: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "delegate";
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /**
         * DeleteGraphResponse
         * @description The outcome of a delete, including whether a project was removed too.
         */
        DeleteGraphResponse: {
            /** Deleted */
            deleted: boolean;
            /** Projectdeleted */
            projectDeleted: boolean;
        };
        /**
         * ExportResponse
         * @description Where the compiled project lives and how to run it.
         */
        ExportResponse: {
            /** Projectpath */
            projectPath: string;
            /** Runcommand */
            runCommand: string;
            /**
             * Target
             * @default pydantic-graph
             * @enum {string}
             */
            target: "pydantic-graph" | "langgraph";
        };
        /**
         * FanoutEdge
         * @description One arm of a multi-successor fan-out.
         *
         *     ``join_node_id`` names the ``join`` node this arm must converge on.
         *     It is required rather than optional because a plain multi-successor
         *     ``add_edge`` pair is silently lossy: ``build()`` accepts it, and only
         *     one arbitrary branch's value survives without an explicit join.
         */
        FanoutEdge: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "fanout";
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Joinnodeid */
            joinNodeId: string;
        };
        /**
         * FindingOut
         * @description One review finding, as the canvas Inspector displays it.
         */
        FindingOut: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Nodeids */
            nodeIds: string[];
        };
        /**
         * GenerateGraphRequest
         * @description Body of ``POST /api/graphs/generate``.
         */
        GenerateGraphRequest: {
            /** Description */
            description: string;
            /** Name */
            name?: string | null;
            /**
             * Graphid
             * @description Reuse an existing graph id (replace its document); default mints a new one.
             */
            graphId?: string | null;
            modelOverride?: components["schemas"]["ModelSelection"] | null;
        };
        /** GenerateGraphResponse */
        GenerateGraphResponse: {
            graph: components["schemas"]["SwarmGraph"];
            /** Warnings */
            warnings: components["schemas"]["FindingOut"][];
            /** Attempts */
            attempts: number;
            model: components["schemas"]["GenerateModelOut"];
        };
        /** GenerateModelOut */
        GenerateModelOut: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Source */
            source: string;
        };
        /**
         * GraphListError
         * @description A graph file that exists on disk but could not be read or validated.
         *
         *     Reported alongside the valid rows rather than replacing them, so one
         *     corrupt file never hides every other saved graph.
         */
        GraphListError: {
            /** Id */
            id: string;
            /** Detail */
            detail: string;
        };
        /**
         * GraphListResponse
         * @description The full ``GET /api/graphs`` response body.
         *
         *     ``errors`` is non-empty only when individual files failed; the request
         *     itself still succeeded.
         */
        GraphListResponse: {
            /** Graphs */
            graphs: components["schemas"]["GraphSummary"][];
            /** Errors */
            errors: components["schemas"]["GraphListError"][];
        };
        /**
         * GraphSummary
         * @description One row of the graph list: enough for a picker, none of the document.
         */
        GraphSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Nodecount */
            nodeCount: number;
            /** Edgecount */
            edgeCount: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description The full ``GET /api/health`` response body.
         */
        HealthResponse: {
            /** Version */
            version: string;
            /** Dshhome */
            dshHome: string;
            /** Settingserror */
            settingsError: string | null;
            resolvedModel: components["schemas"]["ResolvedModelSummary"];
            /** Uvavailable */
            uvAvailable: boolean;
            /** Uvcachedir */
            uvCacheDir: string;
            /** Uvcachewritable */
            uvCacheWritable: boolean;
            /** Workspacedir */
            workspaceDir: string;
            /** Workspacewritable */
            workspaceWritable: boolean;
            /** Webdistpresent */
            webDistPresent: boolean;
            /** Compileready */
            compileReady: boolean;
            /** Blockers */
            blockers: string[];
            /** Runready */
            runReady: boolean;
            /** Runblockers */
            runBlockers: string[];
        };
        /**
         * JoinEdge
         * @description An edge from a fan-out arm's target into the ``join`` node.
         */
        JoinEdge: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "join";
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /**
         * JoinSpec
         * @description Present on ``kind="join"`` nodes: the fan-in reducer.
         *
         *     ``initial_factory`` names the Python builtin the emitter passes as
         *     ``builder.join(..., initial_factory=...)``. When unset, the emitter
         *     derives it from ``reducer`` (``list_append``/``list_extend`` ->
         *     ``list``, ``dict_update`` -> ``dict``, ``sum`` -> ``int``); set it
         *     explicitly only to override that default.
         */
        JoinSpec: {
            /**
             * Reducer
             * @enum {string}
             */
            reducer: "list_append" | "list_extend" | "dict_update" | "sum";
            /** Initialfactory */
            initialFactory?: ("list" | "dict" | "int") | null;
        };
        /**
         * ModelInfoOut
         * @description One entry of a route's explicit model list, as the picker sees it.
         */
        ModelInfoOut: {
            /** Id */
            id: string;
            /** Name */
            name: string | null;
        };
        /**
         * ModelSelection
         * @description One inherited route, resolved to something PydanticAI can
         *     construct (facts 21-24). Absent on :class:`SwarmGraph` means
         *     "inherit the resolved default" rather than "no model".
         */
        ModelSelection: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Reasoningeffort */
            reasoningEffort?: string | null;
        };
        /**
         * ModelsResponse
         * @description The full ``GET /api/models`` response body.
         */
        ModelsResponse: {
            /** Routes */
            routes: components["schemas"]["RouteOut"][];
            resolvedDefault: components["schemas"]["ResolvedDefaultOut"];
            /** Settingserror */
            settingsError: string | null;
        };
        /**
         * NodeIo
         * @description A node's declared input/output port types.
         *
         *     Phase 1 review uses these to reject a port-type mismatch across an
         *     edge and, for a decision's branch targets, to enforce that the
         *     target's ``input_type`` equals the decision's *source step's*
         *     ``output_type`` -- see :class:`DecisionSpec` for why the source step is
         *     the relevant node rather than the decision itself.
         */
        NodeIo: {
            /**
             * Inputtype
             * @enum {string}
             */
            inputType: "str" | "json" | "list[str]";
            /**
             * Outputtype
             * @enum {string}
             */
            outputType: "str" | "json" | "list[str]";
        };
        /**
         * NodeRunRecord
         * @description What one step reported during a run (the last ``node`` frame wins).
         */
        NodeRunRecord: {
            /** Status */
            status: string;
            /** Inputs */
            inputs?: unknown | null;
            /** Output */
            output?: unknown | null;
            /** Statedelta */
            stateDelta?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Durationms */
            durationMs?: number | null;
        };
        /**
         * Position
         * @description Canvas coordinates for a node. Presentation-only: never read by
         *     the emitter, kept purely so the canvas restores node placement.
         */
        Position: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /**
         * ProgrammaticSpec
         * @description Present on ``kind="programmatic"`` nodes: plain-Python steps with
         *     no agent. ``needs`` are extra package requirements the scaffolder
         *     unions into the generated ``pyproject.toml``; ``signature_hint`` is
         *     free-text guidance the fill agent reads (never executed or parsed).
         */
        ProgrammaticSpec: {
            /** Needs */
            needs?: string[];
            /** Signaturehint */
            signatureHint?: string | null;
        };
        /**
         * ResolvedDefaultOut
         * @description The model a compile would use right now, plus where that came from.
         */
        ResolvedDefaultOut: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Source */
            source: string;
        };
        /**
         * ResolvedModelSummary
         * @description The subset of :class:`~swarm_builder.inherit.settings.EffectiveModel`
         *     that is meaningful to a health check. ``reasoning_effort``,
         *     ``base_url``, ``api_key_env``, and ``route`` are internal resolution
         *     detail and are intentionally dropped here (the picker-facing detail
         *     lives in ``/api/models`` instead).
         */
        ResolvedModelSummary: {
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Source */
            source: string;
        };
        /**
         * ReviewResponse
         * @description The Phase-1 review outcome: a pass/fail flag plus every finding.
         */
        ReviewResponse: {
            /** Ok */
            ok: boolean;
            /** Errors */
            errors: components["schemas"]["FindingOut"][];
            /** Warnings */
            warnings: components["schemas"]["FindingOut"][];
        };
        /**
         * RouteOut
         * @description One configured route, with the picker-relevant classification fields.
         *
         *     ``emission``/``required_extra``/``unmappable_reason`` are the outcome
         *     of :func:`swarm_builder.inherit.routes.classify_route`, exposed so the
         *     picker can disable or explain an unusable route before a compile is
         *     attempted.
         */
        RouteOut: {
            /** Key */
            key: string;
            /** Api */
            api: string | null;
            /** Hasexplicitmodels */
            hasExplicitModels: boolean;
            /** Emission */
            emission: string;
            /** Requiredextra */
            requiredExtra: string | null;
            /** Unmappablereason */
            unmappableReason: string | null;
            /** Models */
            models: components["schemas"]["ModelInfoOut"][];
        };
        /** RunListResponse */
        RunListResponse: {
            /** Runs */
            runs: components["schemas"]["RunRecord"][];
        };
        /**
         * RunRecord
         * @description One persisted run.
         */
        RunRecord: {
            /** Runid */
            runId: string;
            /** Graphid */
            graphId: string;
            /** Status */
            status: string;
            /** Createdat */
            createdAt: string;
            /** Finishedat */
            finishedAt?: string | null;
            /** Input */
            input?: unknown | null;
            /** Output */
            output?: unknown | null;
            /** State */
            state?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Model */
            model?: string | null;
            /** Durationms */
            durationMs?: number | null;
            /**
             * Compiled
             * @default false
             */
            compiled: boolean;
            /** Nodes */
            nodes?: {
                [key: string]: components["schemas"]["NodeRunRecord"];
            };
        };
        /**
         * SeqEdge
         * @description A plain sequential edge: ``builder.add_edge(source, target)``.
         */
        SeqEdge: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "seq";
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Label */
            label?: string | null;
        };
        /**
         * StartCompileRequest
         * @description Body of ``POST /api/compile``.
         *
         *     ``target`` selects the export: ``pydantic-graph`` (default, the five
         *     phases) or ``langgraph`` (the five phases, then a conversion of the
         *     validated project into a LangGraph export under
         *     ``workspace/projects-langgraph/<graphId>/``).
         */
        StartCompileRequest: {
            /** Graphid */
            graphId: string;
            /**
             * Target
             * @default pydantic-graph
             * @enum {string}
             */
            target: "pydantic-graph" | "langgraph";
        };
        /**
         * StartCompileResponse
         * @description Body of a successful ``POST /api/compile``.
         *
         *     Only the id: the compile itself runs in the background and reports
         *     everything else through the event stream and the status snapshot.
         */
        StartCompileResponse: {
            /** Compileid */
            compileId: string;
        };
        /**
         * StartRunRequest
         * @description Body of ``POST /api/graphs/:id/runs``.
         *
         *     ``input`` is interpreted by the entry node's ``inputType``
         *     (``compile/run.py``'s ``coerce_input``): a ``str`` port takes the
         *     string verbatim; ``json``/``list[str]`` take the parsed value or a
         *     JSON string of it. ``compileIfStale`` (default on) recompiles a
         *     missing or out-of-date project before running; off, a stale project
         *     is a 409.
         */
        StartRunRequest: {
            /** Input */
            input: unknown;
            /**
             * Compileifstale
             * @default true
             */
            compileIfStale: boolean;
        };
        /** StartRunResponse */
        StartRunResponse: {
            /** Runid */
            runId: string;
            /** Willcompile */
            willCompile: boolean;
        };
        /**
         * StateField
         * @description One field of the generated workflow's ``@dataclass State``.
         *
         *     ``type`` goes through :data:`PORT_TYPE_ANNOTATIONS` like any other
         *     port type when the emitter writes the dataclass field.
         *     ``default`` is literal Python source for the field's default value
         *     (e.g. ``'""'`` or ``"0"``); ``None`` means the emitter writes a bare
         *     ``name: type`` line with no default.
         */
        StateField: {
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "str" | "json" | "list[str]";
            /** Default */
            default?: string | null;
            /** Description */
            description?: string | null;
        };
        /**
         * SwarmGraph
         * @description The complete canvas save file: nodes, edges, state shape, and the
         *     optional per-workflow model override. ``version`` is fixed at ``1``
         *     for this schema generation; a future incompatible shape change ships
         *     as ``version=2`` plus a migration, not a silent field rename.
         */
        SwarmGraph: {
            /**
             * Version
             * @default 1
             * @constant
             */
            version: 1;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Entrynodeid */
            entryNodeId: string;
            /** Exitnodeid */
            exitNodeId: string;
            /** Statefields */
            stateFields?: components["schemas"]["StateField"][];
            /** Nodes */
            nodes?: components["schemas"]["SwarmNode"][];
            /** Edges */
            edges?: (components["schemas"]["SeqEdge"] | components["schemas"]["BranchEdge"] | components["schemas"]["FanoutEdge"] | components["schemas"]["JoinEdge"] | components["schemas"]["DelegateEdge"])[];
            model?: components["schemas"]["ModelSelection"] | null;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /**
         * SwarmNode
         * @description One canvas node.
         *
         *     ``id`` is emitted verbatim as the ``node_id=`` argument to
         *     ``builder.step``/``builder.decision``/``builder.join`` and as the step
         *     module's filename, so it must already be a valid, unique Python
         *     identifier. The frontend is responsible for deriving it from ``title``
         *     via :func:`swarm_builder.slugify.slugify_titles` and keeping it stable
         *     across edits: duplicate titles deduplicate with a numeric suffix, and
         *     the title-to-id mapping must stay stable across recompiles or a
         *     recompile would rename step modules instead of updating them.
         *
         *     Exactly one of ``agent`` / ``programmatic`` / ``decision`` / ``join``
         *     is expected to be set, matching ``kind`` -- enforced by Phase 1
         *     (``review.py``), not here, since that cross-field rule belongs with the
         *     rest of the structural graph validation.
         */
        SwarmNode: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "agent" | "programmatic" | "decision" | "join";
            /** Title */
            title: string;
            /** Intent */
            intent: string;
            position: components["schemas"]["Position"];
            /** Template */
            template?: ("chat" | "orchestrator" | "websearch") | null;
            io: components["schemas"]["NodeIo"];
            /** Reads */
            reads?: string[];
            /** Writes */
            writes?: string[];
            agent?: components["schemas"]["AgentSpec"] | null;
            programmatic?: components["schemas"]["ProgrammaticSpec"] | null;
            decision?: components["schemas"]["DecisionSpec"] | null;
            join?: components["schemas"]["JoinSpec"] | null;
        };
        /**
         * TemplateEntryOut
         * @description The five picker-facing fields of one template catalog entry.
         *
         *     ``deps`` and ``file_manifest`` are internal scaffolding concerns the
         *     picker has no use for, so they are deliberately not exposed.
         */
        TemplateEntryOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Defaulttools */
            defaultTools: string[];
            /** Requiredenv */
            requiredEnv: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_graphs_route_api_graphs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphListResponse"];
                };
            };
        };
    };
    get_graph_route_api_graphs__graph_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwarmGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_graph_route_api_graphs__graph_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwarmGraph"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwarmGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_graph_route_api_graphs__graph_id__delete: {
        parameters: {
            query?: {
                project?: boolean;
            };
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteGraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_graph_route_api_graphs__graph_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateEntryOut"][];
                };
            };
        };
    };
    get_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    export_graph_api_graphs__graph_id__export_get: {
        parameters: {
            query?: {
                target?: "pydantic-graph" | "langgraph";
            };
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_compile_api_compile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartCompileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartCompileResponse"];
                };
            };
            /** @description no such graph */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description a compile is already live for this graph */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description the compile subsystem is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    compile_events_api_compile__compile_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description compile event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Last-Event-ID predates the retained log */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no such compile job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description the compile subsystem is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    compile_status_api_compile__compile_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileSnapshotResponse"];
                };
            };
            /** @description no such compile job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description the compile subsystem is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_compile_api_compile__compile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                compile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompileSnapshotResponse"];
                };
            };
            /** @description no such compile job */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the compile has already finished */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description the compile subsystem is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_runs_route_api_graphs__graph_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_graphs__graph_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunResponse"];
                };
            };
            /** @description no such graph */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description a compile or run is already live, or the project is stale */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the input does not fit the entry node's port type */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the run subsystem is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_run_route_api_graphs__graph_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                graph_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRecord"];
                };
            };
            /** @description no such run record */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_graph_route_api_graphs_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateGraphRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateGraphResponse"];
                };
            };
            /** @description the model could not produce a review-clean graph */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the model API refused or failed the request */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no usable route or credential, or the generator is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
